# Generated by Django 5.0.6 on 2025-05-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_producto_stock'),
        ('apps', '0005_movimientoinventario'),
    ]

    operations = [
    ]
