# Generated by Django 5.0.6 on 2025-05-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_merge_20250519_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={},
        ),
    ]
