# Generated by Django 5.0.6 on 2025-05-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_movimientoinventario_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='estado',
            field=models.IntegerField(default=0),
        ),
    ]
